# Generated by Django 3.0.4 on 2020-03-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('calories', models.IntegerField()),
                ('purchase_date', models.DateTimeField(verbose_name='Date of purchase')),
                ('expiration_date', models.DateTimeField(verbose_name='Date of expiration')),
                ('consumption_date', models.DateTimeField(verbose_name='Date of consumption')),
            ],
        ),
    ]
