# Generated by Django 3.0.4 on 2020-03-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasteless', '0002_auto_20200328_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='parent_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wasteless.List'),
        ),
    ]
